### ISSUE TITLE
Return subset of folders

### ISSUE THREAD

**Issue by presleyd** [do6po/jodit-for-laravel#1]
First of all, great work on this!

I want to have a folder for the various teams in my organization. Each team member would only see their team folder. Do you have a recommendation on how I could achieve this? Could I return a subset of all folders based on user criteria? Or maybe change the base path per user?

**Comment by do6po** [comment]
> First of all, great work on this!
> 
> I want to have a folder for the various teams in my organization. Each team member would only see their team folder. Do you have a recommendation on how I could achieve this? Could I return a subset of all folders based on user criteria? Or maybe change the base path per user?

Hi. I've been very busy lately. I can't find the time to help you yet. Didn't solve the problem?

**Comment by presleyd** [comment]
Not exactly, I switched to CKeditor for other reasons. For that
implementation, I used a middleware to control what resources are shown to
the user. I was just curious how you'd recommend doing that with your setup
but don't worry about me for now. Thanks!
